image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd csharp && dotnet restore && dotnet build --configuration Debug --no-restore
    command: dotnet watch --project ./Tennis.Tests test
  - openMode: split-right
    command: mob status

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9
